config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'home#index'

  get 'auth/:provider/callback', to: 'sessions#create', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/dashboard', to: 'users#show'

  get '/search', to: 'search#index'

  resources :locations, only: %i[show]
  resources :favorites, only: %i[create update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :location

  validates :location, uniqueness: { scope: :user_id }

  scope :active, ->{ where(active: true) }
  scope :eliminated, ->{ where(active: false) }
end

app/models/location.rb
class Location < ApplicationRecord
  include DataUsaClientHelper

  has_many :favorites
  has_many :users, through: :favorites

  
  def name
    city_overview[:display_name]
  end

  def url
    city_overview[:url_name]
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :email, uniqueness: true, presence: true
  validates :google_token, presence: true
  validates :uid, presence: true
  validates :name, presence: true

  has_many :favorites
  has_many :locations, through: :favorites

  def self.update_or_create(auth)
    user = User.find_by(uid: auth[:uid]) || User.new
    user.attributes = {
      uid: auth[:uid],
      email: auth[:info][:email],
      name: auth[:info][:name],
      google_token: auth[:credentials][:token]
    }
    user.save!
    user
  end

  def favorited?(geo_id)
    location = locations.find_by(geo_id: geo_id)
    favorites.active.find_by(location_id: location&.id)
  end

  def eliminated_favorite?(geo_id)
    location = locations.find_by(geo_id: geo_id)
    favorites.eliminated.find_by(location_id: location&.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user
  helper_method :current_user
  # , :require_user

  def current_user
    @current_user ||= User.find(session[:id]) if session[:id]
  end

  # def require_user
  #   unless current_user
  #     flash[:error] = 'You must be signed in for that action'
  #     redirect_to root_path
  #   end
  # end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  helper_method :favorite, :location

  def create
    if favorite && !favorite&.active?
      favorite.update_attributes(active: true)
    else
      current_user.locations << location
    end

    redirect_to dashboard_path
  end

  def update
    if favorite.active?
      favorite.update_attributes(active: false)
    else
      flash[:error] = 'Something went wrong with unfavoriting this location'
    end

    redirect_to dashboard_path
  end

  private

  def location
    @location ||= Location.find_or_create_by(geo_id: params[:geo_id])
  end

  def favorite
    @favorite ||= current_user.favorites.find_by(location: location)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/locations_controller.rb
# frozen_string_literal: true

class LocationsController < ApplicationController
  helper_method :city
  
  def show; end

  private

  def city
    @city = CityInformation.new(params[:id])
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController

  def index
    city_search
  end

  private

  def city_search
    @city_search = CityFinder.new(params[:q])
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController <ApplicationController

  def create
    user = User.update_or_create(auth_hash)
    session[:id] = user.id
    redirect_to dashboard_path
  end

  def destroy
  session[:id] = nil
  # session[:id].clear
    redirect_to root_path
  end

  def auth_hash
    request.env["omniauth.auth"]
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  helper_method :favorites

  def show
    favorites
  end

  private

  def favorites
    @favorites ||= current_user.favorites.active
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class='row my-auto'>
  <div class='col-12 text-center'>
    <h1>Smooth Move</h1>
    <%= link_to "/auth/google_oauth2", class: 'btn btn-outline-primary' do %>
      <%= image_tag 'btn_google_light_normal_ios.svg', class: 'img-fluid' %>
      <span>Sign in with Google</span>
    <% end %>
  </div>
  <div class='col-12 text-center mt-5'>
    <%= image_tag 'Destination_NewOrleans_page.jpg', class: 'img-fluid' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmoothMove</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.linearicons.com/free/1.0.0/svgembedder.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    
    <div class='container p-1'>
      <%= yield %>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/locations/show.html.erb
  <div class='col-12 mx-auto'>
    <div class='row text-center'>
      <div class='col-12'>
        <% if current_user.favorited?(city.geo_id) %>
          <%= form_tag favorite_path(geo_id: city.geo_id), { action: 'update', method: :put } do %>
            <%= hidden_field_tag :geo_id, city.geo_id  %>
            <%= submit_tag 'Unfavorite', type: 'submit', class: "btn btn-primary" , method: :put%>
          <% end %>
        <% else %>
          <% if current_user.eliminated_favorite?(city.geo_id) %>
            <p>You previously favorited this location</p>
          <% end %>
          <%= form_tag :favorites, { action: 'create' } do %>
            <%= hidden_field_tag :geo_id, city.geo_id  %>
            <%= submit_tag 'Favorite', type: 'submit', class: "btn btn-primary" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>


<div class="d-flex p-2 flex-row justify-content-start">
  <div class="bd-highlight flex-grow-1 text-center">

    <div class="d-flex mt-3 justify-content-around align-items-start">
      <div class="flex-row">
          <div class="bd-highlight text-center">
          <h4></h4>
          <br/>
            <h1 class="display-4">
              <%= city.city_name %>
            </h1>
            <h4>
              <a class="text-info" >
               Median Age <%= city.average_age %> years
              </a>
            </h4>
            <br/>
          </div>
          <div class="bd-highlight text-center">
            <h4>Population</h4>
            <h1 class="display-4">
              <%= number_with_delimiter(city.population, delimiter: ',') %>
            </h1>
            <h4>
              <a class="text-info" >
               Ranked <%= city.pop_rank.ordinalize %>
              </a>
            </h4>
            <br/>
          </div>
        </div>

        <div class="flex-row">
          <div class="bd-highlight text-center">
            <h4>Median Income</h4>
            <h1 class="display-4">
              <%= number_to_currency(city.average_income, precision: 0) %>
            </h1>
            <h4>
              <a class="text-info" >
                Ranked <%= city.income_rank.ordinalize %>
              </a>
            </h4>
            <br/>
          </div>
          <div class="bd-highlight text-center">
            <h4>Median Property Value</h4>
              <h1 class="display-4">
                <%= number_to_currency(city.average_property_value, precision: 0) %>
              </h1>
            <h4>
              <a class="text-info" >
                Owner Occupied Homes <%= city.owner_occupied %>%
              </a>
            </h4>
          </div>
        </div>
    </div>
  </div>

  <div class="bd-highlight flex-grow-1 text-center">
    <div class="col-sm-12">
      <h1>Ethnicity Breakdown</h1>
      <h5 class="ml-1 text-muted"></h5>
      <%= bar_chart(city.ethnicity_hash) %>
    </div>

  </div>
</div>



<div class="d-flex p-2 flex-column">
  <h1>Transportation</h1>
  <h4>Mean Commute Time: <%= city.mean_commute %> minutes</h4>
  <h5 class="ml-2 text-muted"></h5>
  <%= pie_chart(city.transport_hash) %>
</div>

app/views/partials/_breadcrumbs.html.erb
<%= render_breadcrumbs :separator => ' / ' %>

app/views/search/index.html.erb
<div class='row'>
  <div class='col-12 mt-3'>
    <%= render 'partials/breadcrumbs' %>
  </div>
</div>

<div class='row mt-5'>
  <% @city_search.city_matches.each do |match| %>
    <div class='col-12 col-md-6 col-lg-4 my-3'>
      <div class='card rounded shadow'>
        <div class='row'>
          <div class='col-12'>
            <h5 class='card-title text-center my-2'><%= "#{match.city_name}" %></h5>
            <div class='card-body d-flex justify-content-between'>
              <div class='text-right col'>
                <%= link_to 'View', location_path(id: match.geo_id), class: 'btn btn-primary col' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<%# if current_user %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Smooth Move</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <% if current_user%>
        <li class="nav-item active">
          <%= link_to 'Dashboard', dashboard_path, class: 'nav-link' %>
        </li>
        <% end %>
      </ul>
        <%= form_tag :search, method: :get, class: "search-box form-inline" do %>
          <div class="form-group search-field">
            <%= text_field_tag :q, nil, placeholder: 'Enter City', class: "form-control mr-2" %>
            <%= submit_tag 'Search', class: 'btn btn-outline-primary my-2 my-sm-0' %>
          </div>
        <% end %>
      <div class='ml-5'>
        <% if current_user %>
          <%= link_to 'Log Out', logout_path, class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </nav>
<%# end %>

app/views/users/show.html.erb
<h1>Welcome <%= current_user.name %></h1>
<h4>Active Favorites: <%= current_user.favorites.active.count %></h4>

<div class="list-group">
  <% current_user.favorites.active.each do |favorite| %>
    <%= link_to location_path(id: favorite.location.geo_id),
                class: 'list-group-item list-group-item-action favorites' do %>
      <div class="d-flex w-100 justify-content-between">          
        <h5 class="mb-1"><%= favorite.location.name %></h5>
        <small>Saved <%= time_ago_in_words(favorite.updated_at) %> ago</small>
      </div>
    <% end %>
  <% end %>
</div>